version: '2'
services:
  pg:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: ./config/api/Dockerfile
    environment:
      NODE_PATH: ${NODE_PATH}
      API_PORT: ${API_DEV_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_SECRET: ${REDIS_SECRET}
      DOMAIN: ${DOMAIN}
    tty: true
    volumes:
      - ./api/src:/usr/api/src
      - ./api/tests:/usr/api/tests
    command: ${CMD}
    links:
      - "pg:pg"
      - "redis:redis"
  nginx:
    image: nginx
    volumes:
      - ./app/dist/:/var/www/
      - ./config/nginx-api.conf:/etc/nginx/conf.d/default.conf
    environment:
     - NGINX_PORT=${PROD_PORT}
    ports:
      - "${PROD_PORT}:${PROD_PORT}"
    links:
      - "api:api"
      - "redis:redis"
    depends_on:
      - "api"
